on: [push]
jobs:
  Kicad-Generate-Gerbs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Run KiCad actions
      uses: actions-for-kicad/kicad-actions@v1.4-k9.0.2
      with:
        schematic_file_name: ./board/led_matrix.kicad_sch
        symbol_libraries: "led_matrix=../lib/symbols/led_matrix.kicad_sym"
        run_erc: false
        schematic_output_pdf: true
        schematic_output_bom: true
  
        pcb_file_name: ./board/led_matrix.kicad_pcb
        footprint_libraries: "led_matrix=../lib/footprints/led_matrix.pretty"
        run_drc: false
        pcb_output_gerbers_and_drill: true
        pcb_output_image: true

    - name: Upload schematic
      uses: actions/upload-artifact@v4
      with:
        name: Schematic
        path: ./board/schematic.pdf

    - name: Upload BOM
      uses: actions/upload-artifact@v4
      with:
        name: BOM
        path: ./board/bom.csv

    - name: Upload gerbers and drill file
      uses: actions/upload-artifact@v4
      with:
        name: Gerbers
        path: ./board/gerbers

    - name: Upload image render
      uses: actions/upload-artifact@v4
      with:
        name: Image render
        path: ./board/pcb.png
